### PR TITLE
Add verbose and error stream output to Receive-RSJob

### PR DESCRIPTION
**Pull request by martin9700**
Wasn't sure if you wanted to keep helper functions in the Private functions group but since this only applies to Receive-RSJob I put it here.

### CODE REVIEW

**Comment by proxb** [comment]
Weird that it failed on tests that you weren't even covering in this pull request. I'll dig into this tomorrow and if everything looks OK, I'll merge the pull request.

**Comment by proxb** [comment]
I re-ran he build against my current commit and it passed without issue. Still need to download the code here and see where the Pester test is failing at.

**Comment by martin9700** [comment]
Looked like it was having trouble with the PoshRS.PowerShell.RSJob type in the Param section of my function.  I could change that to [object] and that would probably work too.

**Comment by martin9700** [comment]
Making some enhancements to this, and following your private function format a little closer.

**Pull request closed without merging**
